# Generated by Django 4.1.3 on 2024-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Час продажу'),
        ),
    ]
