services:
  web: 
    build:
      context: ./site
      dockerfile: Dockerfile
    
    container_name: site
    restart: always

    ports: 
      - '8000:8000'
    
    volumes:
      - ./site:/site
      - site-database:/site/.dblocal

volumes:
  site-database: