# Generated by Django 4.1.3 on 2024-01-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sold_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час продажу'),
        ),
    ]
