# Generated by Django 4.1.3 on 2024-01-31 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_carproducer_options_alter_partproducer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст запиту')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_requests', to=settings.AUTH_USER_MODEL, verbose_name='Від користувача')),
                ('to_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auto', verbose_name='До авто')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Пропозиція')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='selection.selectionrequest', verbose_name='Запит')),
            ],
        ),
    ]
