# Generated by Django 4.1.3 on 2024-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_selectionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Очікує на підбір'), (2, 'Підбір здійснено'), (3, 'Підбір прийнято'), (4, 'Підбір відхилено')], default=1, verbose_name='Статус підбору'),
        ),
    ]
