# Generated by Django 4.1.3 on 2024-01-31 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_alter_selectionrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата подачі заявки'),
            preserve_default=False,
        ),
    ]
