# Generated by Django 4.1.3 on 2024-01-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_part_amount_part_articul_part_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='barcode',
            field=models.CharField(default=83476582736492840, max_length=255, verbose_name='Штрих-код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='fuel',
            field=models.CharField(choices=[('0', 'Бензин'), ('1', 'Електро'), ('2', 'Дизель'), ('3', 'Гібрид')], max_length=255, verbose_name='Тип палива'),
        ),
        migrations.AlterField(
            model_name='carproducer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='part',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.auto', verbose_name='Автомобіль'),
        ),
    ]
