# Generated by Django 4.1.3 on 2024-01-17 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_part_barcode_alter_auto_fuel_alter_carproducer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='owners',
            field=models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
