# Generated by Django 4.1.3 on 2024-01-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_owners_partunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now=True, verbose_name='Дата продажі')),
                ('buy_price', models.FloatField(blank=True, verbose_name='Закупочна ціна')),
                ('sell_price', models.FloatField(blank=True, verbose_name='Роздрібна ціна')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.part', verbose_name='Назва')),
            ],
        ),
    ]
