# Generated by Django 4.1.3 on 2024-01-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_sold_at'),
        ('main', '0006_partunit_order_partunit_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partunit',
            name='sale_date',
        ),
        migrations.AlterField(
            model_name='partunit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.order', verbose_name='Замовлення'),
        ),
    ]
