# Generated by Django 4.1.3 on 2024-01-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_partunit_sale_date_alter_partunit_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Імя')),
                ('about', models.TextField(verbose_name='Опис')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.partproducer', verbose_name='Виробник'),
        ),
    ]
