# Generated by Django 4.1.3 on 2024-01-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_partproducer_part_producer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carproducer',
            options={'verbose_name': 'Марка авто', 'verbose_name_plural': 'Марки авто'},
        ),
        migrations.AlterModelOptions(
            name='partproducer',
            options={'verbose_name': 'Виробник запчастини', 'verbose_name_plural': 'Виробники запчастин'},
        ),
        migrations.AlterField(
            model_name='auto',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carproducer', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='partproducer',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='partproducer',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Імя'),
        ),
    ]
