# Generated by Django 4.1.3 on 2024-03-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_carproducer_options_alter_partproducer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.carproducer', verbose_name='Марка'),
        ),
    ]
