# Generated by Django 4.1.3 on 2024-03-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_auto_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/%Y/%m/%d/', verbose_name='Фото товару'),
        ),
    ]
