# Generated by Django 4.1.3 on 2024-03-07 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ідентифікатор телеграм аккаунта')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Імя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Нікнейм')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tg_account', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
