# Generated by Django 4.1.3 on 2024-01-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('region', models.CharField(max_length=100, verbose_name='Область')),
                ('city', models.CharField(max_length=100, verbose_name='Населений пункт')),
                ('office_number', models.PositiveIntegerField(verbose_name='Номер відділення')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL, verbose_name='Адреса доставки')),
            ],
        ),
    ]
